### ISSUE TITLE
多个项目环境配置的名称一致时创建用例集后选环境保存会报错

### ISSUE THREAD

**Issue by AzoraLeo** [HttpRunner/FasterRunner#41]
项目A创建了一个环境配置：测试环境
项目B创建了一个环境配置：测试环境
项目A新建用例集，选择测试环境和其他用例，保存报错，保存接口的传参是环境配置的名称，存在同名就报错了，改了其中一个环境配置的名称后就正常

**Comment by yinquanwang** [comment]
已修复，等待更新
